Added support for HypeTrain Event Subscription via WebHook
d-fischer/twitch pull request #175
Opened 2020-09-14 21:21 UTC by HoodyBooti

Type: 

Fixes: #

Adds support to subscribe to the HypeTrain Event

2020-09-14 21:30 UTC, d-fischer requested changes

2020-09-14 21:30 UTC, d-fischer commented on packages/twitch/src/API/Helix/WebHooks/HelixWebHooksApi.ts
> +	 * Unsubscribes from events representing a user following other users.
This doc block seems to suffer from copypasta ;)

2020-09-14 21:30 UTC, d-fischer commented on packages/twitch/src/API/Helix/HypeTrain/HypeTrainEvent.ts
> +	lastContribution: HypeTrainContributor;
Did you mean `HypeTrainContributorData`? You're also gonna need to properly convert the data to class instances in the getters.

2020-09-15 16:40 UTC, d-fischer requested changes

2020-09-15 16:40 UTC, d-fischer commented on packages/twitch/src/API/Helix/HypeTrain/HypeTrainEvent.ts
> +		this._data.lastContribution = new HypeTrainContributor(_data.lastContribution);
Please don't overwrite raw data with class instances. Instead, convert in the getters, as I said.

2020-09-15 16:44 UTC, d-fischer commented
Before I can merge this (regardless of any other changes necessary), please rebase away the file deletions so proper change attribution is kept.

2020-09-16 21:47 UTC, billygerhard commented on packages/twitch/src/API/Helix/HypeTrain/HypeTrainContributor.ts
> +	 * A Twitch Partner.
This comment doesn't make sense. Was this copy pasta from something else?

2020-10-06 21:08 UTC, d-fischer commented
Was this even tested at all? While rebasing and fixing up the problems that were already found, I found more copypasta, both in comments and in actual code, making it impossible to work. Also, the data interface definitions aren't close to the actual data from Twitch.

2020-10-07 17:40 UTC, Technikkeller approved these changes
LGTM

2020-10-11 18:37 UTC, d-fischer approved these changes

2020-10-11 18:37 UTC, merged