add 'created_at' to HelixUser
d-fischer/twitch pull request #212
Opened 2021-01-23 20:39 UTC by Rydann

Type: Bugfix
Fixes: #211

Add the missing `created_at` response field that was added with the Developer Day in November 2020.

Ref: https://twitch.uservoice.com/forums/310213-developers/suggestions/37682716-add-created-timestamp-to-helix-users

2021-01-23 21:09 UTC, d-fischer requested changes
In addition to the given change, please rebase this onto `version/4.4`.

Also, the issue you created should really be of the feature request type. If you had used the feature request template, you would have known that you should be waiting for a response between issue and pull request creation (and you wouldn't have to rebase now).

2021-01-23 21:09 UTC, d-fischer commented on packages/twitch/src/API/Helix/User/HelixUser.ts
> +		return this._data.created_at;
All timestamps in this library are wrapped in a `Date` object. Please change this getter accordingly.

2021-01-23 21:33 UTC, Rydann commented
Yeah sorry my bad, fixed.

2021-01-23 22:32 UTC, d-fischer commented
Merging is not rebasing. This PR now pollutes the commit history unnecessarily, especially for such a small change.

2021-01-24 06:07 UTC, closed without merging

2021-01-24 06:09 UTC, Rydann commented
Will submit a new and proper pull request, remind me to never try to submit one again after being awake for too long. 🙃